
baseURL: "https://chandleru11.github.io/"
languageCode: en-US
title: Chandler Underwood
theme: hugo-PaperMod
homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog
# profile-mode

params:
  profileMode:
    enabled: true
    title: "Hello!" # optional default will be site title
    subtitle: "Welcome to my portfolio. As I'm sure you're wondering...yes, I do a little modeling, and I have been published (once) - not in a magazine but in an academic journal. Somewhat funny jokes aside, my name is Chandler, and I'm a serious data scientist. I love learning and using data to solve problems, and I feel very lucky to have the opportunity to work in this awesome field. I hope you enjoy your time here while you check out my background and projects!"
    imageUrl: "screenshot.png" # optional
    imageTitle: "blah" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/ChandlerU11"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/chandler-underwood-421bbb162/"
    - name: "strava"
      url: "https://www.strava.com/athletes/55427636"

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20 
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 30      
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 40 
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 50
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 60